views/main_views.py
import functools

from flask import Flask, request, redirect, url_for
from flask import Blueprint, request, render_template, url_for, current_app, session, g, flash, jsonify
from werkzeug.security import generate_password_hash
from werkzeug.utils import redirect

from main import args
from models import update_crop_image, get_images, get_detail, get_summary, get_statistics, get_loss
from form import SupervisingForm

# blueprint
bp = Blueprint('main', __name__, url_prefix='/')

def confidence():
    pass

@bp.route('/')
def index():
    return render_template('base.html')

@bp.route('/summary/')
def summary():
    page = int(request.args.get('page', 1))
    # filename = request.args.get('filename', None)
    paging, img_list, total = get_summary(page=page)
    return render_template('train/summary.html', **locals())

@bp.route('/prediction/')
def prediction():
    page = int(request.args.get('page', 1))
    # filename = request.args.get('filename', None)
    paging, img_list, crop_imgs = get_images(page=page)
    return render_template('train/train.html', **locals())

@bp.route('/detail/', methods=('GET', 'POST'))
def detail():
    form = SupervisingForm()
    if request.method == 'POST' and form.validate_on_submit():
        filename = form.filename.data
        order = form.order.data
        target = form.target.data
        request_data = {'path_folder':args.result_folder + filename.split('.')[0], 'order':int(order), 'target':target}
        update_crop_image(request_data)

    page = int(request.args.get('page', 1))
    filename = request.args.get('filename', None)
    paging, crop_imgs = get_detail(page=page, filename=filename)
    return render_template('train/detail.html', **locals())

@bp.route('/statistics/')
def statistics():
    xy_list, path_list, confidence_list = get_statistics()
    return render_template('train/statistics.html', **locals())

@bp.route('/loss/')
def loss():
    loss_data = get_loss()
    model_list = []
    epoch_list = []
    loss_list = {}
    accuracy_list = {}
    colors = ['#ff0000', '#0000ff', '#7FFFD4', '#ff8397', '#6970d5']
    for model in loss_data:
        epochs = []
        model_list.append(model)
        loss_list[model] = []
        accuracy_list[model] = []
        for data in loss_data[model]:
            epochs.append(data['epoch'])
            loss_list[model].append(data['loss'])
            accuracy_list[model].append(data['accuracy'])
        if epoch_list:
            if len(epoch_list) < len(epochs):
                epoch_list = epochs
        else:
            epoch_list = epochs
    return render_template('train/loss.html', **locals())

views/upload_views.py
import os
import datetime

from flask import Blueprint, request, render_template, url_for, jsonify 
from werkzeug.utils import redirect

import torch
import torch.backends.cudnn as cudnn

from main import args
from recognition import pipeline
from recognition.craft import CRAFT
from recognition.model import Model
from recognition.utils import CTCLabelConverter, AttnLabelConverter

# device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# blueprint
bp = Blueprint('upload', __name__, url_prefix='/upload')
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'jfif', 'xlsx'])

def execute_detection_model():
    # load net
    net = CRAFT()

    print('Loading detection model from %s' %args.detection_model)
    if args.cuda:
        net.load_state_dict(pipeline.copyStateDict(torch.load(args.detection_model)))
    else:
        net.load_state_dict(pipeline.copyStateDict(torch.load(args.detection_model, map_location='cpu')))

    if args.cuda:
        net = net.cuda()
        net = torch.nn.DataParallel(net)
        cudnn.benchmark = False

    net.eval()

    # LinkRefiner
    refine_net = None
    if args.refine:
        from recognition.refinenet import RefineNet

        refine_net = RefineNet()
        print('Loading refiner model from %s' %args.refiner_model)
        if args.cuda:
            refine_net.load_state_dict(pipeline.copyStateDict(torch.load(args.refiner_model)))
            refine_net = refine_net.cuda()
            refine_net = torch.nn.DataParallel(refine_net)
        else:
            refine_net.load_state_dict(pipeline.copyStateDict(torch.load(args.refiner_model, map_location='cpu')))
        refine_net.eval()
        args.poly = True
    return net, refine_net

def excute_recognition_model():
    """Open csv file wherein you are going to write the Predicted Words"""
    if 'CTC' in args.Prediction:
        converter = CTCLabelConverter(args.character)
    else:
        converter = AttnLabelConverter(args.character)
    args.num_class = len(converter.character)

    if args.rgb:
        args.input_channel = 3
    model = Model(args)
    model.to(device)
    #model = torch.nn.DataParallel(model).to(device)

    # load model
    print('Loading recognition model from %s' %args.recognition_model)
    model.load_state_dict(torch.load(args.recognition_model, map_location=device))

    return model, converter

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def ocr(file):
    prediction = []
    if file and allowed_file(file.filename):
        ext = file.filename.split('.')[-1]
        filename = str(datetime.datetime.now().strftime('%Y%m%d%H%M%S')) + '.' + ext
        file_path = os.path.join(args.upload_folder, filename)
        file.save(file_path)
        prediction = pipeline.execute_ocr(filename, file_path, net=net, refine_net=refine_net, model=model, converter=converter)
    return prediction

@bp.route('/', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        file = request.files['file']
        ocr(file)
        return redirect(url_for('main.prediction'))
    return render_template('upload.html')

@bp.route('/predict', methods=['POST'])
def predict():
    file = request.files['file']
    prediction = ocr(file)
    return jsonify(prediction)

net, refine_net = execute_detection_model()
model, converter = excute_recognition_model()

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>OcrWeb</title>
    <meta charset="utf-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
</head>
<body>
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
<!-- ------------------------------ [edit] -------------------------------- -->
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}
<!-- ---------------------------------------------------------------------- -->

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">OcrWeb</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.logout') }}">{{ g.user.name }} (logout)</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('upload.upload_file') }}">upload</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.summary') }}">summary</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.prediction') }}">prediction</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.statistics') }}">statistics</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.loss') }}">loss</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('upload.upload_file') }}">upload</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.summary') }}">summary</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.prediction') }}">prediction</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.statistics') }}">statistics</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.loss') }}">loss</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

templates/paging.html
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if paging.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?page=1&filename={{ filename }}">처음</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="?page={{ paging.prev_num }}&filename={{ filename }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in paging.pages %}
        {% if page_num %}
            {% if page_num != paging.page %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}&filename={{ filename }}">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_num }}</a>
            </li>
            {% endif %}
        {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if paging.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ paging.next_num }}&filename={{ filename }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
</ul>

templates/upload.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <h1>Upload new File</h1>
    <form action="" method=post enctype=multipart/form-data>
      <p><input type=file name=file>
         <input type=submit value=Upload>
    </form>
</div>
{% endblock %}